setw -g xterm-keys on
set-window-option -g xterm-keys on
set -s escape-time 0
set -sg repeat-time 300
set -s focus-events on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g mouse on
set -sg exit-empty on
set -g history-limit 10000

# unbind C-b
# set -g prefix 'C-s'
#
# set -g base-index 1
# set -g pane-base-index 1
# setw -g automatic-rename on
# set -g renumber-windows on
#
# set -g display-panes-time 2000
# set -g display-time 2000
#
# bind c new-window -c "#{pane-current-path}"
# bind j split-window -vb -c "#{pane-current-path}"
# bind k split-window -v -c "#{pane-current-path}"
# bind h split-window -hb -c "#{pane-current-path}"
# bind l split-window -h -c "#{pane-current-path}"
#
# bind -n C-x kill-pane
#
# bind -n C-f resize-pane -Z
#
# bind -n C-j select-pane -D
# bind -n C-k select-pane -U
# bind -n C-h select-pane -L
# bind -n C-l select-pane -R
#
# bind -n C-J resize-pane -D
# bind -n C-K resize-pane -U
# bind -n C-H resize-pane -L
# bind -n C-L resize-pane -R
#
# bind -n C-Space next-layout
#
# set -g mode-keys vi
# bind -n C-y copy-mode
#
# bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
# bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy"
#
# bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi j send-keys -X cursor-down
# bind -T copy-mode-vi k send-keys -X cursor-up
# bind -T copy-mode-vi h send-keys -X cursor-left
# bind -T copy-mode-vi l send-keys -X cursor-right
# bind -T copy-mode-vi J send-keys -N 5 -X cursor-down
# bind -T copy-mode-vi K send-keys -N 5 -X cursor-up
# bind -T copy-mode-vi H send-keys -N 5 -X cursor-left
# bind -T copy-mode-vi L send-keys -N 5 -X cursor-right
# bind -T copy-mode-vi I send-keys -X start-of-line
# bind -T copy-mode-vi A send-keys -X end-of-line
# bind -T copy-mode-vi Y send-keys -X copy-end-of-line
#
# unbind n
# unbind p
# unbind 1
# unbind 2
# unbind 3
# unbind 4
# unbind 5
# unbind 6
# unbind 7
# unbind 8
# unbind 9
# unbind 0
#
# bind -n C-p previous-window
# bind -n C-n next-window
#
# bind -n C-1 select-window -t 1
# bind -n C-2 select-window -t 2
# bind -n C-3 select-window -t 3
# bind -n C-4 select-window -t 4
# bind -n C-5 select-window -t 5
# bind -n C-6 select-window -t 6
# bind -n C-7 select-window -t 7
# bind -n C-8 select-window -t 8
# bind -n C-9 select-window -t 9
#
# set -g status-bg black
# set -g status-fg white

# set-option default-path "$PWD"

#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'erikw/tmux-powerline'
#
#run '~/.tmux/plugins/tpm/tpm'

# set-option -g status-utf8 on
# set -g status-right '#(rainbarf)'

